name: Main Workflow
on: [push]
env:
  #pushの度に適切な値に更新
  db_image_name: mysql:5.7 
  aci_db_name: wordpressdb
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # リポジトリのチェック
    - name: Checkout GitHub Action
      uses: actions/checkout@main
      
    # Azureへのログイン
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      
    - name: Deploy DB Container to ACI
      uses: azure/aci-deploy@v1.1.3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        name: ${{ env.aci_db_name }}
        image: ${{ env.db_image_name }}
        vnet-name: aci-vnet
        subnet-name: aci-subnet
        ports: 3306
        location: japanwest
        environment-variables: MYSQL_ROOT_PASSWORD=somewordpress,MYSQL_DATABASE=wordpress,MYSQL_USER=wordpress,MYSQL_PASSWORD=wordpress
        azure-file-volume-share-name: db-fileshare
        azure-file-volume-account-name: odacontainerstorage
        azure-file-volume-account-key: ${{ secrets.ASA_Key }}
        azure-file-volume-mount-path: /var/lib/mysql
